### ISSUE TITLE
Use name convention for extension registration

### ISSUE THREAD

**Issue by everzet** [laracasts/Behat-Laravel-Extension#1]
In Behat 3 you don't need to provide a full extension classname when you're registering extensions, you can use a shorter version and Behat will guess the rest (if you follow naming convention, of course):
https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/ServiceContainer/ExtensionManager.php#L116-L129

Because of that line, if your extension class name looks like `{YourOrg}\{YourName}Extension\ServiceContainer\{YourName}Extension`, then you can simply use `{YourOrg}\{YourName}Extension` as an extension name in `behat.yml`. For example instead of:

``` yml
default:
    extensions:
        Behat\MinkExtension\ServiceContainer\MinkExtension: ~
```

you could say:

``` yml
default:
    extensions:
        Behat\MinkExtension: ~
```

So if you rename your `Laracasts\Behat\ServiceContainer\LaravelExtension` class to `Laracasts\Behat\ServiceContainer\BehatExtension`, then people would be able to register your extension with just:

``` yml
default:
    extensions:
        Laracasts\Behat: ~
```
