### ISSUE TITLE
The @javascript tag cannot be used without enabling a javascript session

### ISSUE THREAD

**Issue by sdeering** [laracasts/Behat-Laravel-Extension#27]
In this tutorial https://laracasts.com/series/the-lifecycle-of-a-new-feature/episodes/2 it says to add @Javascript to the feature in order to see it perform the test live in the browser. But this error appears:

![image](https://cloud.githubusercontent.com/assets/1787454/6591948/d3ce93a4-c812-11e4-92ae-f67d1b8c34c5.png)

Any ideas?

**Comment by doug7410** [comment]
I am dealing with the same problem. Would love some help.

**Comment by punkpette** [comment]
I had that issue i needed to specify a javascript_session on behat.yml 
however if i try to use selenium2 it doesn't seem to work

**Comment by alnutile** [comment]
@sdeering i know it is a year later. But just incase someone else sees this and so the ticket can be closed what solution worked for you?

For my my behat.yml set to

```
    Laracasts\Behat:
      env_path: .env.behat
    Behat\MinkExtension:
      base_url: https://foo.dev
      default_session: laravel
      laravel: ~
      selenium2:
        wd_host: "http://selenium-server.dev:4444/wd/hub"
      browser_name: chrome
```

And including in composer require-dev

```
        "behat/mink-selenium2-driver": "^1.3",
```

Will allow me fo use the @javascript tag.
