### ISSUE TITLE
Exception: Class could not be loaded

### ISSUE THREAD

**Issue by webkenny** [laracasts/Behat-Laravel-Extension#35]
I've watched the video on Laracasts, tried the code listed in `README` for this extension, and played around with various different incantations of including the extensions but nothing works. No matter what I do it always comes up with the below error when I run `behat`:

```
[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]                     
`Laracasts\Behat\ServiceContainer\BehatExtension` extension file or class could not be located.
```

First attempt from my `behat.yml` based on the video:

```
  extensions:
    Laracasts\Behat\ServiceContainer\LaracastsExtension: ~
    Behat\MinkExtension\ServiceContainer\MinkExtension:
        default_session: laravel
        laravel: ~
```

Second attempt, based on discovering the class name had changed and the comments:

```
  extensions:
    Laracasts\Behat\ServiceContainer\BehatExtension: ~
    Behat\MinkExtension\ServiceContainer\MinkExtension:
        default_session: laravel
        laravel: ~
```

Third attempt based on what the repository says:

```
default:
    extensions:
        Laracasts\Behat:
            # env_path: .env.behat
        Behat\MinkExtension:
            default_session: laravel
            laravel: ~
```

Am I missing something here? Fatal errors every time. 

(Oh the stinging irony in wanting to test but not being able to get the test runner to run. Ha!)
