### ISSUE TITLE
Cipher issue

### ISSUE THREAD

**Issue by alnutile** [laracasts/Behat-Laravel-Extension#52]
Had an problem with APP_KEY not getting passed to here

vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:37

Need to make sure it is not regression in my behat library

![screenshot 2016-09-11 17 15 53](https://cloud.githubusercontent.com/assets/365385/18420585/be8f35a6-7843-11e6-9cc6-6c4129026992.png)

My fix for now was to add 

```
default:
    extensions:
        Laracasts\Behat:
            env_path: .env
        Behat\MinkExtension:
            base_url: https://teamdocs-leanpub.dev
            default_session: laravel
            laravel: ~
            selenium2:
              wd_host: "http://selenium-server.dev:4444/wd/hub"
            browser_name: chrome
```

env_path: .env 
instead of leaving it commented out?

Was there are regression somewhere on this?
