### ISSUE TITLE
Behat only running 1st Scenario

### ISSUE THREAD

**Issue by catharsisjelly** [laracasts/Behat-Laravel-Extension#70]
Hi there,

I'm using this to begin to test an API that I am working on. My `.feature` has several Scenarios in but Behat is only running the first one for some reason. Would you have any clue as to why?

My behat.yml file
```
default:
    extensions:
        Laracasts\Behat:
            env_path: .env.behat
        Behat\MinkExtension:
            base_url: http://localhost:8080
            default_session: laravel
            laravel: ~

    gherkin:
        filters:
            tags: ~@skip

    suites:
        default:
            paths: [ %paths.base%/tests/Feature ]
            contexts:
                - Tests\Feature\Context\APIClientContext:
                - Tests\Feature\Context\BusinessContext:
                - Tests\Feature\Context\FeatureContext:
```

Let me know if you need any more info.

**Comment by catharsisjelly** [comment]
Hey,

Just thought I would say that I resolved this today, the reason it was happening is because I had Behat had no idea where MinkContext was since none of Contexts was extending them. Fix was as follows

```
    suites:
        default:
            paths: [ %paths.base%/tests/Feature ]
            contexts:
                - Tests\Feature\Context\APIClientContext:
                - Tests\Feature\Context\BusinessContext:
                - Behat\MinkExtension\Context\MinkContext:
```
