### ISSUE TITLE
Laravel 5.5 no longer works

### ISSUE THREAD

**Issue by devmsh** [laracasts/Behat-Laravel-Extension#72]
Can anyone help in resolving that problem?

the `MinkExtenstion` seems to be updated and the package no longer works

I currently use 
```
default:
    extensions:
        Behat\MinkExtension:
            base_url:  'http://localhost/tdl/public'
            sessions:
              default:
                goutte: ~
```

But once I added the laravel related estenstion
```
        Laracasts\Behat:
```

the following error appear when I run the features test

```
In RemoveUnusedDefinitionsPass.php line 75:
                                             
  Serialization of 'Closure' is not allowed  
```

Any help?
