### ISSUE TITLE
Behat dependency injection is not working, replaced by Laravel's DI

### ISSUE THREAD

**Issue by tentacode** [laracasts/Behat-Laravel-Extension#84]
Hello there ! Just a little thing that bugs me, you can't use Behat's own dependency injection system (it's not documented a lot so not a lot of person are using it) you can learn more about it here :

* [https://github.com/Behat/Behat/pull/974](https://github.com/Behat/Behat/pull/974)
* [http://www.tentacode.net/behat-dependency-injection-phpdi](http://www.tentacode.net/behat-dependency-injection-phpdi)

So, for example, this does not work : 

``` 
    suites:
        default:
            contexts:
                - Contexts\Api\JsonContext:
                    - '@api_client'
            services:
                api_client: 
                    class: "Contexts\\Api\\Service\\ApiClient"
                    arguments: ['http://127.0.0.1:8000']
```

And produce the error :

```
In LaravelArgumentResolver.php line 48:

  [ErrorException]
  substr() expects parameter 1 to be string, object given

Exception trace:
 () at /Users/gabriel/Workspace/taskl/vendor/laracasts/behat-laravel-extension/src/Context/Argument/LaravelArgumentResolver.php:48
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at n/a:n/a
```

This is because `LaravelArgumentResolver` only resolve argument "Laravel way" and don't care if the argument has aleady be resolved by Behat (which is the case here). This can be solved by changing the behat.yml to  :

```
    suites:
        default:
            contexts:
                - Contexts\Api\JsonContext:
                    - '@Contexts\Api\Service\ApiClient'
```

But this forces us to use Laravel DI (and I can't set constructor arguments in behat.yml this way).

This is probably an easy fix, I could do it if I take the time, at least it's documented now :) Thanks for the good work.
